AWSTemplateFormatVersion: "2010-09-09"
Resources:
  responsesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "JsonFile"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "JsonFile"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "metadata"
